name: Python Control Structures Assignment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run tests for while loop
        run: python3 tests/test_assignment.py TestControlStructures.test_while_loop

      - name: Run tests for for loop with continue
        run: python3 tests/test_assignment.py TestControlStructures.test_for_loop_continue

      - name: Run tests for if-else statement
        run: python3 tests/test_assignment.py TestControlStructures.test_if_else

      - name: Run tests for nested loops
        run: python3 tests/test_assignment.py TestControlStructures.test_nested_loops
